version: 2

_default: &default
  docker:
    - image: circleci/node:latest
  working_directory: ~/repo

jobs:
  pdf:
    docker:
      - image: aergus/latex:latest
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install python3 python3-venv
      - checkout
      - run:
          name: Install pandoc-guides
          command: |
            git clone https://github.com/AntoineAugusti/pandoc-guides.git /tmp/pandoc-guides
            cp /tmp/pandoc-guides/* .
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Generate PDF files
          command: |
            source venv/bin/activate
            python main.py producteurs-schemas "Créer un schéma de données" pdf/guide-schema.pdf
            python main.py juridique "Identifier les données à ouvrir" pdf/guide-juridique.pdf
      - store_artifacts:
          path: pdf
  lint-md:
    <<: *default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Lint Markdown files
          command: |
            npm run lint-md
  extended-lint-md:
    <<: *default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Lint Markdown files
          command: |
            npm run extended-lint-md
workflows:
  version: 2
  commit:
    jobs:
      - lint-md
      - pdf
  cron:
    triggers:
      - schedule:
          cron: "20 1 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - extended-lint-md
